[tool.flake8]
max-line-length = 120
ignore = ["E203", "W503", "E501", "F401"]
exclude = [".git", "__pycache__", "build", "dist"]

[tool.pylint.messages_control]
disable = [
    "missing-docstring",
    "too-few-public-methods", 
    "too-many-arguments",
    "too-many-locals",
    "too-many-branches",
    "too-many-statements",
    "line-too-long",
    "unused-argument",
    "import-error"
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.typecheck] 
ignored-modules = ["homeassistant", "homeassistant.core", "homeassistant.helpers", "homeassistant.components", "voluptuous"]

[tool.pylint.variables]
dummy-variables-rgx = "_+$|(_[a-zA-Z0-9_]*[a-zA-Z0-9]+?$)|dummy|^ignored_|^unused_"

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true